name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile --non-interactive --prefer-offline

      - name: Run type check
        run: bun run typecheck

      - name: Run linting
        run: bun run check

      - name: Run tests
        run: bun run test

      - name: Token list check
        run: ./scripts/generate-token-list-schema.sh

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        run: supabase db start

      - name: Verify generated types are checked in
        run: |
          supabase gen types --lang=typescript --local > src/types/database-generated.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet src/types/database-generated.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
