name: Security Analysis

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  security_analysis:
    name: Shared
    uses: aurora-is-near/.github/.github/workflows/security_analysis.yml@master
    secrets: inherit
